# in-place variable syntax
@url = http://localhost:3001


###
GET {{url}}/

###
POST {{url}}/users

{
    "name": "asd",
    "username": "asd1@gmail.com",
    "password": "asdasd"
}

###
POST {{url}}/users/login

{
    "username": "asd1@gmail.com",
    "password": "asdasd"
}

###
GET {{url}}/users/get

### TODO: 

###
POST {{url}}/users/send

{
    "content": "khong dieu kien 1"
}

